version: '2'

services:
    web:
        links:
             - db
        image: 926803513772.dkr.ecr.eu-west-1.amazonaws.com/cccd:latest
        ports:
            - "8000:80"
        depends_on:
            - db
        env_file:
            cccd-dev-env.txt

    db:
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=testuser
            - POSTGRES_PASSWORD=yourPassword
            - POSTGRES_DB=cbo_development
